// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cinitialize_values
List cinitialize_values(NumericVector y, NumericVector ini_par, double h);
RcppExport SEXP _svjmcmc_cinitialize_values(SEXP ySEXP, SEXP ini_parSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ini_par(ini_parSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cinitialize_values(y, ini_par, h));
    return rcpp_result_gen;
END_RCPP
}
// cmcmc
NumericVector cmcmc(NumericVector y, NumericVector ini_par, int g, int G, double h, double echo);
RcppExport SEXP _svjmcmc_cmcmc(SEXP ySEXP, SEXP ini_parSEXP, SEXP gSEXP, SEXP GSEXP, SEXP hSEXP, SEXP echoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ini_par(ini_parSEXP);
    Rcpp::traits::input_parameter< int >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type echo(echoSEXP);
    rcpp_result_gen = Rcpp::wrap(cmcmc(y, ini_par, g, G, h, echo));
    return rcpp_result_gen;
END_RCPP
}
// crjsize_i
double crjsize_i(double jtime_i, double vim1, double vi, double yi, double mu, double k, double theta, double sigma_v, double rho, double lmbd, double sigma_j, double h);
RcppExport SEXP _svjmcmc_crjsize_i(SEXP jtime_iSEXP, SEXP vim1SEXP, SEXP viSEXP, SEXP yiSEXP, SEXP muSEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigma_vSEXP, SEXP rhoSEXP, SEXP lmbdSEXP, SEXP sigma_jSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type jtime_i(jtime_iSEXP);
    Rcpp::traits::input_parameter< double >::type vim1(vim1SEXP);
    Rcpp::traits::input_parameter< double >::type vi(viSEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type lmbd(lmbdSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_j(sigma_jSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crjsize_i(jtime_i, vim1, vi, yi, mu, k, theta, sigma_v, rho, lmbd, sigma_j, h));
    return rcpp_result_gen;
END_RCPP
}
// crjtime_i
double crjtime_i(double jsize_i, double vim1, double vi, double yi, double mu, double k, double theta, double sigma_v, double rho, double lmbd, double sigma_j, double h);
RcppExport SEXP _svjmcmc_crjtime_i(SEXP jsize_iSEXP, SEXP vim1SEXP, SEXP viSEXP, SEXP yiSEXP, SEXP muSEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigma_vSEXP, SEXP rhoSEXP, SEXP lmbdSEXP, SEXP sigma_jSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type jsize_i(jsize_iSEXP);
    Rcpp::traits::input_parameter< double >::type vim1(vim1SEXP);
    Rcpp::traits::input_parameter< double >::type vi(viSEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type lmbd(lmbdSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_j(sigma_jSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crjtime_i(jsize_i, vim1, vi, yi, mu, k, theta, sigma_v, rho, lmbd, sigma_j, h));
    return rcpp_result_gen;
END_RCPP
}
// crk
double crk(double prior_mu, double prior_var, NumericVector v, NumericVector y, NumericVector jsize, NumericVector jtime, double mu, double theta, double sigma_v, double rho, double h);
RcppExport SEXP _svjmcmc_crk(SEXP prior_muSEXP, SEXP prior_varSEXP, SEXP vSEXP, SEXP ySEXP, SEXP jsizeSEXP, SEXP jtimeSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP sigma_vSEXP, SEXP rhoSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prior_mu(prior_muSEXP);
    Rcpp::traits::input_parameter< double >::type prior_var(prior_varSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jsize(jsizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jtime(jtimeSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crk(prior_mu, prior_var, v, y, jsize, jtime, mu, theta, sigma_v, rho, h));
    return rcpp_result_gen;
END_RCPP
}
// crlambda
double crlambda(double prior_a, double prior_b, NumericVector jtime);
RcppExport SEXP _svjmcmc_crlambda(SEXP prior_aSEXP, SEXP prior_bSEXP, SEXP jtimeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prior_a(prior_aSEXP);
    Rcpp::traits::input_parameter< double >::type prior_b(prior_bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jtime(jtimeSEXP);
    rcpp_result_gen = Rcpp::wrap(crlambda(prior_a, prior_b, jtime));
    return rcpp_result_gen;
END_RCPP
}
// crmu
double crmu(double prior_mu, double prior_var, NumericVector v, NumericVector y, NumericVector jsize, NumericVector jtime, double k, double theta, double sigma_v, double rho, double h);
RcppExport SEXP _svjmcmc_crmu(SEXP prior_muSEXP, SEXP prior_varSEXP, SEXP vSEXP, SEXP ySEXP, SEXP jsizeSEXP, SEXP jtimeSEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigma_vSEXP, SEXP rhoSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prior_mu(prior_muSEXP);
    Rcpp::traits::input_parameter< double >::type prior_var(prior_varSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jsize(jsizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jtime(jtimeSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crmu(prior_mu, prior_var, v, y, jsize, jtime, k, theta, sigma_v, rho, h));
    return rcpp_result_gen;
END_RCPP
}
// crrho
double crrho(double rho_old, NumericVector v, NumericVector y, NumericVector jsize, NumericVector jtime, double mu, double k, double theta, double sigma_v, double h);
RcppExport SEXP _svjmcmc_crrho(SEXP rho_oldSEXP, SEXP vSEXP, SEXP ySEXP, SEXP jsizeSEXP, SEXP jtimeSEXP, SEXP muSEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigma_vSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho_old(rho_oldSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jsize(jsizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jtime(jtimeSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crrho(rho_old, v, y, jsize, jtime, mu, k, theta, sigma_v, h));
    return rcpp_result_gen;
END_RCPP
}
// crsigma_j
double crsigma_j(double prior_shape, double prior_scale, NumericVector jsize);
RcppExport SEXP _svjmcmc_crsigma_j(SEXP prior_shapeSEXP, SEXP prior_scaleSEXP, SEXP jsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prior_shape(prior_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type prior_scale(prior_scaleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jsize(jsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(crsigma_j(prior_shape, prior_scale, jsize));
    return rcpp_result_gen;
END_RCPP
}
// crsigma_v
double crsigma_v(double sigma_v_old, double prior_shape, double prior_rate, NumericVector v, NumericVector y, NumericVector jsize, NumericVector jtime, double mu, double k, double theta, double rho, double h);
RcppExport SEXP _svjmcmc_crsigma_v(SEXP sigma_v_oldSEXP, SEXP prior_shapeSEXP, SEXP prior_rateSEXP, SEXP vSEXP, SEXP ySEXP, SEXP jsizeSEXP, SEXP jtimeSEXP, SEXP muSEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP rhoSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma_v_old(sigma_v_oldSEXP);
    Rcpp::traits::input_parameter< double >::type prior_shape(prior_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type prior_rate(prior_rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jsize(jsizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jtime(jtimeSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crsigma_v(sigma_v_old, prior_shape, prior_rate, v, y, jsize, jtime, mu, k, theta, rho, h));
    return rcpp_result_gen;
END_RCPP
}
// crtheta
double crtheta(double prior_mu, double prior_var, NumericVector v, NumericVector y, NumericVector jsize, NumericVector jtime, double mu, double k, double sigma_v, double rho, double h);
RcppExport SEXP _svjmcmc_crtheta(SEXP prior_muSEXP, SEXP prior_varSEXP, SEXP vSEXP, SEXP ySEXP, SEXP jsizeSEXP, SEXP jtimeSEXP, SEXP muSEXP, SEXP kSEXP, SEXP sigma_vSEXP, SEXP rhoSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prior_mu(prior_muSEXP);
    Rcpp::traits::input_parameter< double >::type prior_var(prior_varSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jsize(jsizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type jtime(jtimeSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crtheta(prior_mu, prior_var, v, y, jsize, jtime, mu, k, sigma_v, rho, h));
    return rcpp_result_gen;
END_RCPP
}
// crv0
double crv0(double v0_old, double prior_shape, double prior_rate, double v1, double y1, double jsize_1, double jtime_1, double mu, double k, double theta, double sigma_v, double rho, double h);
RcppExport SEXP _svjmcmc_crv0(SEXP v0_oldSEXP, SEXP prior_shapeSEXP, SEXP prior_rateSEXP, SEXP v1SEXP, SEXP y1SEXP, SEXP jsize_1SEXP, SEXP jtime_1SEXP, SEXP muSEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigma_vSEXP, SEXP rhoSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v0_old(v0_oldSEXP);
    Rcpp::traits::input_parameter< double >::type prior_shape(prior_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type prior_rate(prior_rateSEXP);
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< double >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< double >::type jsize_1(jsize_1SEXP);
    Rcpp::traits::input_parameter< double >::type jtime_1(jtime_1SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crv0(v0_old, prior_shape, prior_rate, v1, y1, jsize_1, jtime_1, mu, k, theta, sigma_v, rho, h));
    return rcpp_result_gen;
END_RCPP
}
// crvN
double crvN(double vN_old, double vNm1, double yN, double jsize_N, double jtime_N, double mu, double k, double theta, double sigma_v, double rho, double h);
RcppExport SEXP _svjmcmc_crvN(SEXP vN_oldSEXP, SEXP vNm1SEXP, SEXP yNSEXP, SEXP jsize_NSEXP, SEXP jtime_NSEXP, SEXP muSEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigma_vSEXP, SEXP rhoSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type vN_old(vN_oldSEXP);
    Rcpp::traits::input_parameter< double >::type vNm1(vNm1SEXP);
    Rcpp::traits::input_parameter< double >::type yN(yNSEXP);
    Rcpp::traits::input_parameter< double >::type jsize_N(jsize_NSEXP);
    Rcpp::traits::input_parameter< double >::type jtime_N(jtime_NSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crvN(vN_old, vNm1, yN, jsize_N, jtime_N, mu, k, theta, sigma_v, rho, h));
    return rcpp_result_gen;
END_RCPP
}
// crvi
double crvi(double vi_old, double vim1, double vip1, double yi, double yip1, double jsize_i, double jsize_ip1, double jtime_i, double jtime_ip1, double mu, double k, double theta, double sigma_v, double rho, double h);
RcppExport SEXP _svjmcmc_crvi(SEXP vi_oldSEXP, SEXP vim1SEXP, SEXP vip1SEXP, SEXP yiSEXP, SEXP yip1SEXP, SEXP jsize_iSEXP, SEXP jsize_ip1SEXP, SEXP jtime_iSEXP, SEXP jtime_ip1SEXP, SEXP muSEXP, SEXP kSEXP, SEXP thetaSEXP, SEXP sigma_vSEXP, SEXP rhoSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type vi_old(vi_oldSEXP);
    Rcpp::traits::input_parameter< double >::type vim1(vim1SEXP);
    Rcpp::traits::input_parameter< double >::type vip1(vip1SEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type yip1(yip1SEXP);
    Rcpp::traits::input_parameter< double >::type jsize_i(jsize_iSEXP);
    Rcpp::traits::input_parameter< double >::type jsize_ip1(jsize_ip1SEXP);
    Rcpp::traits::input_parameter< double >::type jtime_i(jtime_iSEXP);
    Rcpp::traits::input_parameter< double >::type jtime_ip1(jtime_ip1SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crvi(vi_old, vim1, vip1, yi, yip1, jsize_i, jsize_ip1, jtime_i, jtime_ip1, mu, k, theta, sigma_v, rho, h));
    return rcpp_result_gen;
END_RCPP
}
// crSVJ
NumericVector crSVJ(double v_0, double n_segment, NumericVector par, int N, double h);
RcppExport SEXP _svjmcmc_crSVJ(SEXP v_0SEXP, SEXP n_segmentSEXP, SEXP parSEXP, SEXP NSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v_0(v_0SEXP);
    Rcpp::traits::input_parameter< double >::type n_segment(n_segmentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(crSVJ(v_0, n_segment, par, N, h));
    return rcpp_result_gen;
END_RCPP
}
// gen_data_SVJ
void gen_data_SVJ(std::string par_name, NumericVector par, int N, int N_rep, double h, double n_segment);
RcppExport SEXP _svjmcmc_gen_data_SVJ(SEXP par_nameSEXP, SEXP parSEXP, SEXP NSEXP, SEXP N_repSEXP, SEXP hSEXP, SEXP n_segmentSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type par_name(par_nameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type N_rep(N_repSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type n_segment(n_segmentSEXP);
    gen_data_SVJ(par_name, par, N, N_rep, h, n_segment);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_svjmcmc_cinitialize_values", (DL_FUNC) &_svjmcmc_cinitialize_values, 3},
    {"_svjmcmc_cmcmc", (DL_FUNC) &_svjmcmc_cmcmc, 6},
    {"_svjmcmc_crjsize_i", (DL_FUNC) &_svjmcmc_crjsize_i, 12},
    {"_svjmcmc_crjtime_i", (DL_FUNC) &_svjmcmc_crjtime_i, 12},
    {"_svjmcmc_crk", (DL_FUNC) &_svjmcmc_crk, 11},
    {"_svjmcmc_crlambda", (DL_FUNC) &_svjmcmc_crlambda, 3},
    {"_svjmcmc_crmu", (DL_FUNC) &_svjmcmc_crmu, 11},
    {"_svjmcmc_crrho", (DL_FUNC) &_svjmcmc_crrho, 10},
    {"_svjmcmc_crsigma_j", (DL_FUNC) &_svjmcmc_crsigma_j, 3},
    {"_svjmcmc_crsigma_v", (DL_FUNC) &_svjmcmc_crsigma_v, 12},
    {"_svjmcmc_crtheta", (DL_FUNC) &_svjmcmc_crtheta, 11},
    {"_svjmcmc_crv0", (DL_FUNC) &_svjmcmc_crv0, 13},
    {"_svjmcmc_crvN", (DL_FUNC) &_svjmcmc_crvN, 11},
    {"_svjmcmc_crvi", (DL_FUNC) &_svjmcmc_crvi, 15},
    {"_svjmcmc_crSVJ", (DL_FUNC) &_svjmcmc_crSVJ, 5},
    {"_svjmcmc_gen_data_SVJ", (DL_FUNC) &_svjmcmc_gen_data_SVJ, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_svjmcmc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
